BCSystem.Web/Models/Endereco.cs
namespace BCSystem.Web.Models
{
    public class Endereco
    {
        public string CEP { get; set; }

        public string Logradouro { get; set; }

        public int Numero { get; set; } 

        public string Complemento { get; set;}

        public string Bairro { get; set; }

        public string Cidade { get; set; }

        public UF UF { get; set; }
        
    }
}

BCSystem.Web/Models/Fornecedor.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace BCSystem.Web.Models
{
    public class Fornecedor
    {
        [BsonId]
        [BsonRepresentation(BsonType.String)]
        public Guid Id { get; set; }

        public string CEP { get; set; }

        public string Logradouro { get; set; }

        public string CPForCNPJ { get; set; }

        public string Nome {  get; set; }

        public string Telefone { get; set; }    

        public string Email { get; set; }       

        public Endereco Endereco { get; set; }
    }
}

BCSystem.Web/Models/Produto.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

public class Produto
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; }
    public string Nome { get; set; }
    public int CodigoProduto { get; set; }
    public decimal Preco { get; set; }
    public decimal PrecoVenda { get; set; }
    public string Categoria { get; set; }
    public string Marca { get; set; }

}

BCSystem.Web/Models/UF.cs
namespace BCSystem.Web.Models
{
    public class UF
    {
        public string UFSigla { get; set; }
        public string Nome { get; set; }
    }
}

BCSystem.Web/Controllers/FornecedorController.cs
using BCSystem.Web.Models;
using Microsoft.AspNetCore.Mvc;


public class FornecedorController : Controller
{
    private readonly FornecedorRepositorio _repository;

    public FornecedorController(FornecedorRepositorio repository)
    {
        _repository = repository;
    }

    public async Task<IActionResult> Index()
    {
        List<Fornecedor> Fornecedors = await _repository.GetAllFornecedors();
        return View(Fornecedors);
    }

    public async Task<IActionResult> Details(Guid id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var Fornecedor = await _repository.GetFornecedor(id);
        if (Fornecedor == null)
        {
            return NotFound();
        }

        return View(Fornecedor);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Fornecedor Fornecedor)
    {
        await _repository.CreateFornecedor(Fornecedor);
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Edit(Guid id)
    {
        Fornecedor Fornecedor = await _repository.GetFornecedor(id);
        return View(Fornecedor);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Guid id, Fornecedor Fornecedor)
    {
        await _repository.UpdateFornecedor(id, Fornecedor);
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Delete(Guid id)
    {
        Fornecedor Fornecedor = await _repository.GetFornecedor(id);
        return View(Fornecedor);
    }

    [HttpPost]
    public async Task<IActionResult> DeleteConfirmed(Guid id)
    {
        await _repository.DeleteFornecedor(id);
        return RedirectToAction("Index");
    }
}

BCSystem.Web/Controllers/HomeController.cs
using BCSystem.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BCSystem.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BCSystem.Web/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;


public class ProdutoController : Controller
{
    private readonly ProdutoRepositorio _repository;

    public ProdutoController(ProdutoRepositorio repository)
    {
        _repository = repository;
    }

    public async Task<IActionResult> Index()
    {
        List<Produto> produtos = await _repository.GetAllProdutos();
        return View(produtos);
    }

    public async Task<IActionResult> Details(string id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var produto = await _repository.GetProduto(id);
        if (produto == null)
        {
            return NotFound();
        }

        return View(produto);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Produto produto)
    {
        await _repository.CreateProduto(produto);
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Edit(string id)
    {
        Produto produto = await _repository.GetProduto(id);
        return View(produto);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(string id, Produto produto)
    {
        await _repository.UpdateProduto(id, produto);
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Delete(string id)
    {
        Produto produto = await _repository.GetProduto(id);
        return View(produto);
    }

    [HttpPost]
    public async Task<IActionResult> DeleteConfirmed(string id)
    {
        await _repository.DeleteProduto(id);
        return RedirectToAction("Index");
    }
}

BCSystem.Web/Views/Fornecedor/Create.cshtml
@model Fornecedor

<h1>Criar Novo Fornecedor</h1>

<form asp-action="Create">
    <div class="form-group">
        <label for="CPForCNPJ">CPF/CNPJ:</label>
        <input type="text" class="form-control" id="CPForCNPJ" name="CPForCNPJ" required>
    </div>
    <div class="form-group">
        <label for="Nome">Nome:</label>
        <input type="text" class="form-control" id="Nome" name="Nome" required>
    </div>
    <div class="form-group">
        <label for="Telefone">Telefone:</label>
        <input type="text" class="form-control" id="Telefone" name="Telefone" required>
    </div>
    <div class="form-group">
        <label for="Email">Email:</label>
        <input type="email" class="form-control" id="Email" name="Email" required>
    </div>
    <div class="form-group">
        <label for="Endereco.CEP">CEP:</label>
        <input type="text" class="form-control" id="Endereco.CEP" name="Endereco.CEP" required>
    </div>
    <div class="form-group">
        <label for="Endereco.Logradouro">Logradouro:</label>
        <input type="text" class="form-control" id="Endereco.Logradouro" name="Endereco.Logradouro" required>
    </div>
    <div class="form-group">
        <label for="Endereco.Numero">Número:</label>
        <input type="number" class="form-control" id="Endereco.Numero" name="Endereco.Numero" required>
    </div>
    <div class="form-group">
        <label for="Endereco.Complemento">Complemento:</label>
        <input type="text" class="form-control" id="Endereco.Complemento" name="Endereco.Complemento">
    </div>
    <div class="form-group">
        <label for="Endereco.Bairro">Bairro:</label>
        <input type="text" class="form-control" id="Endereco.Bairro" name="Endereco.Bairro" required>
    </div>
    <div class="form-group">
        <label for="Endereco.Cidade">Cidade:</label>
        <input type="text" class="form-control" id="Endereco.Cidade" name="Endereco.Cidade" required>
    </div>
    <div class="form-group">
        <label for="Endereco.UF.UFSigla">UF:</label>
        <input type="text" class="form-control" id="Endereco.UF.UFSigla" name="Endereco.UF.UFSigla" required>
    </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

<a class="btn btn-secondary" asp-action="Index">Voltar</a>

BCSystem.Web/Views/Fornecedor/Delete.cshtml
@model Fornecedor

<h1>Excluir Fornecedor</h1>

<h3>Tem certeza de que deseja excluir este fornecedor?</h3>
<div>
    <h4>CPF/CNPJ: @Model.CPForCNPJ</h4>
    <h4>Nome: @Model.Nome</h4>
    <h4>Telefone: @Model.Telefone</h4>
    <h4>Email: @Model.Email</h4>
    <h4>CEP: @Model.Endereco.CEP</h4>
    <h4>Logradouro: @Model.Endereco.Logradouro</h4>
    <h4>Número: @Model.Endereco.Numero</h4>
    <h4>Complemento: @Model.Endereco.Complemento</h4>
    <h4>Bairro: @Model.Endereco.Bairro</h4>
    <h4>Cidade: @Model.Endereco.Cidade</h4>
    <h4>UF: @Model.Endereco.UF.UFSigla</h4>
</div>

<form asp-action="DeleteConfirmed" asp-route-id="@Model.Id">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger">Excluir</button>
    <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
</form>

BCSystem.Web/Views/Fornecedor/DeleteConfirmed.cshtml
<h1>Fornecedor Excluído</h1>

<p>O fornecedor foi excluído com sucesso.</p>

<a class="btn btn-primary" asp-action="Index">Voltar para a Lista de Fornecedores</a>

BCSystem.Web/Views/Fornecedor/Details.cshtml
@model Fornecedor

<h1>Detalhes do Fornecedor</h1>

<div>
    <h4>ID: @Model.Id</h4>
    <h4>CPF/CNPJ: @Model.CPForCNPJ</h4>
    <h4>Nome: @Model.Nome</h4>
    <h4>Telefone: @Model.Telefone</h4>
    <h4>Email: @Model.Email</h4>
    <h4>CEP: @Model.Endereco.CEP</h4>
    <h4>Logradouro: @Model.Endereco.Logradouro</h4>
    <h4>Número: @Model.Endereco.Numero</h4>
    <h4>Complemento: @Model.Endereco.Complemento</h4>
    <h4>Bairro: @Model.Endereco.Bairro</h4>
    <h4>Cidade: @Model.Endereco.Cidade</h4>
    <h4>UF: @Model.Endereco.UF.UFSigla</h4>
</div>

<a class="btn btn-primary" asp-action="Index">Voltar para a Lista</a>

BCSystem.Web/Views/Fornecedor/Edit.cshtml
@model Fornecedor

<h1>Editar Fornecedor</h1>

<form asp-action="Edit" asp-route-id="@Model.Id">
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label for="CPForCNPJ">CPF/CNPJ:</label>
        <input type="text" class="form-control" id="CPForCNPJ" name="CPForCNPJ" value="@Model.CPForCNPJ" required>
    </div>
    <div class="form-group">
        <label for="Nome">Nome:</label>
        <input type="text" class="form-control" id="Nome" name="Nome" value="@Model.Nome" required>
    </div>
    <div class="form-group">
        <label for="Telefone">Telefone:</label>
        <input type="text" class="form-control" id="Telefone" name="Telefone" value="@Model.Telefone" required>
    </div>
    <div class="form-group">
        <label for="Email">Email:</label>
        <input type="email" class="form-control" id="Email" name="Email" value="@Model.Email" required>
    </div>
    <div class="form-group">
        <label for="Endereco.CEP">CEP:</label>
        <input type="text" class="form-control" id="Endereco.CEP" name="Endereco.CEP" value="@Model.Endereco.CEP" required>
    </div>
    <div class="form-group">
        <label for="Endereco.Logradouro">Logradouro:</label>
        <input type="text" class="form-control" id="Endereco.Logradouro" name="Endereco.Logradouro" value="@Model.Endereco.Logradouro" required>
    </div>
    <div class="form-group">
        <label for="Endereco.Numero">Número:</label>
        <input type="number" class="form-control" id="Endereco.Numero" name="Endereco.Numero" value="@Model.Endereco.Numero" required>
    </div>
    <div class="form-group">
        <label for="Endereco.Complemento">Complemento:</label>
        <input type="text" class="form-control" id="Endereco.Complemento" name="Endereco.Complemento" value="@Model.Endereco.Complemento">
    </div>
    <div class="form-group">
        <label for="Endereco.Bairro">Bairro:</label>
        <input type="text" class="form-control" id="Endereco.Bairro" name="Endereco.Bairro" value="@Model.Endereco.Bairro" required>
    </div>
    <div class="form-group">
        <label for="Endereco.Cidade">Cidade:</label>
        <input type="text" class="form-control" id="Endereco.Cidade" name="Endereco.Cidade" value="@Model.Endereco.Cidade" required>
    </div>
    <div class="form-group">
        <label for="Endereco.UF.UFSigla">UF:</label>
        <input type="text" class="form-control" id="Endereco.UF.UFSigla" name="Endereco.UF.UFSigla" value="@Model.Endereco.UF.UFSigla" required>
    </div>
    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

<a class="btn btn-secondary" asp-action="Index">Voltar</a>

BCSystem.Web/Views/Fornecedor/Index.cshtml
@model List<Fornecedor>

<h1>Lista de Fornecedores</h1>

<table class="table">
    <thead>
        <tr>
            <th>CPF/CNPJ</th>
            <th>Nome</th>
            <th>Telefone</th>
            <th>Email</th>
            <th>CEP</th>
            <th>Logradouro</th>
            <th>Número</th>
            <th>Complemento</th>
            <th>Bairro</th>
            <th>Cidade</th>
            <th>UF</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var fornecedor in Model)
        {
            <tr>
                <td>@fornecedor.CPForCNPJ</td>
                <td>@fornecedor.Nome</td>
                <td>@fornecedor.Telefone</td>
                <td>@fornecedor.Email</td>
                <td>@fornecedor?.Endereco?.CEP</td>
                <td>@fornecedor?.Endereco?.Logradouro</td>
                <td>@fornecedor?.Endereco?.Numero</td>
                <td>@fornecedor?.Endereco?.Complemento</td>
                <td>@fornecedor?.Endereco?.Bairro</td>
                <td>@fornecedor?.Endereco?.Cidade</td>
                <td>@fornecedor?.Endereco?.UF?.UFSigla</td>
                <td><a asp-action="Edit" asp-route-id="@fornecedor?.Id">Editar</a></td>
                <td><a asp-action="Details" asp-route-id="@fornecedor?.Id">Detalhes</a></td>
                <td><a asp-action="Delete" asp-route-id="@fornecedor?.Id">Excluir</a></td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-primary" asp-action="Create">Novo Fornecedor</a>

BCSystem.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BCSystem.Web/Views/Produto/Create.cshtml
@model Produto

<h1>Criar Novo Produto</h1>

<form asp-action="Create">
    <div class="form-group">
        <label for="Nome">Nome:</label>
        <input type="text" class="form-control" id="Nome" name="Nome" required>
    </div>
    <div class="form-group">
        <label for="CodigoProduto">Codigo Produto:</label>
        <input type="text" class="form-control" id="CodigoProduto" name="CodigoProduto" required>
    </div>
    <div class="form-group">
        <label for="Preco">Preço:</label>
        <input type="text" class="form-control" id="Preco" name="Preco" required>
    </div>
    <div class="form-group">
        <label for="PrecoVenda">Preço Venda:</label>
        <input type="text" class="form-control" id="PrecoVenda" name="PrecoVenda" required>
    </div>
    <div class="form-group">
        <label for="Categoria">Categoria:</label>
        <input type="text" class="form-control" id="Categoria" name="Categoria" required>
    </div>
    <div class="form-group">
        <label for="Marca">Marca:</label>
        <input type="text" class="form-control" id="Marca" name="Marca" required>
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

<a class="btn btn-secondary" asp-action="Index">Voltar</a>

BCSystem.Web/Views/Produto/Delete.cshtml
@model Produto

<h1>Excluir Produto</h1>

<h3>Tem certeza de que deseja excluir este produto?</h3>
<div>
    <h4>Nome: @Model.Nome</h4>
    <h4>Preço: @Model.Preco</h4>
</div>

<form asp-action="DeleteConfirmed" asp-route-id="@Model.Id">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger">Excluir</button>
    <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
</form>

BCSystem.Web/Views/Produto/DeleteConfirmed.cshtml
<h1>Produto Excluído</h1>

<p>O produto foi excluído com sucesso.</p>

<a class="btn btn-primary" asp-action="Index">Voltar para a Lista de Produtos</a>

BCSystem.Web/Views/Produto/Details.cshtml
@model Produto

<h1>Detalhes do Produto</h1>

<div>
    <h4>Nome: @Model.Nome</h4>
    <h4>Preço: @Model.CodigoProduto</h4>
    <h4>Preço: @Model.Preco</h4>
    <h4>Preço: @Model.PrecoVenda</h4>
    <h4>Preço: @Model.Categoria</h4>
    <h4>Preço: @Model.Marca</h4>  
</div>

<a asp-action="Index">Voltar para a Lista</a>

BCSystem.Web/Views/Produto/Edit.cshtml
@model Produto

<h1>Editar Produto</h1>

<form asp-action="Edit" asp-route-id="@Model.Id">
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label for="Nome">Nome:</label>
        <input type="text" class="form-control" id="Nome" name="Nome" value="@Model.Nome" required>
    </div>
    <div class="form-group">
        <label for="CodigoProduto">Preço:</label>
        <input type="text" class="form-control" id="CodigoProduto" name="CodigoProduto" value="@Model.CodigoProduto" required>
    </div>
    <div class="form-group">
        <label for="Preco">Preço:</label>
        <input type="text" class="form-control" id="Preco" name="Preco" value="@Model.Preco" required>
    </div>
    <div class="form-group">
        <label for="PrecoVenda">Preço Venda:</label>
        <input type="text" class="form-control" id="PrecoVenda" name="PrecoVenda" value="@Model.PrecoVenda" required>
    </div>
    <div class="form-group">
        <label for="Categoria">Categoria:</label>
        <input type="text" class="form-control" id="Categoria" name="Categoria" value="@Model.Categoria" required>
    </div>
    <div class="form-group">
        <label for="Marca">Marca:</label>
        <input type="text" class="form-control" id="Marca" name="Marca" value="@Model.Marca" required>
    </div>    
    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

<a class="btn btn-secondary" asp-action="Index">Voltar</a>

BCSystem.Web/Views/Produto/Index.cshtml
@model List<Produto>

<h1>Lista de Produtos</h1>

<table class="table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Preço</th>
            <th>CodigoProduto</th>
            <th>PrecoVenda</th>
            <th>Categoria</th>
            <th>Marca</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var produto in Model)
        {
            <tr>
                <td>@produto.Nome</td>
                <td>@produto.Preco</td>
                <td>@produto.CodigoProduto</td>
                <td>@produto.PrecoVenda</td>
                <td>@produto.Categoria</td>
                <td>@produto.Marca</td>                
                <td><a asp-action="Edit" asp-route-id="@produto.Id">Editar</a></td>
                <td><a asp-action="Details" asp-route-id="@produto.Id">Detalhes</a></td>
                <td><a asp-action="Delete" asp-route-id="@produto.Id">Excluir</a></td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-primary" asp-action="Create">Novo Produto</a>

BCSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BCSystem.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BCSystem.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BCSystem.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fornecedor" asp-action="Index">Fornecedor </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BCSystem.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>